config/routes.rb
Rails.application.routes.draw do
  root 'customers#new'
  post 'customers' => 'customers#create'
  get 'obrigado' => 'customers#obrigado'
  get 'google8346493cd4fccd96.html' => 'customers#google8346493cd4fccd96'
  get 'video_position' => "customers#track_video_played"
  get ':professional_website', to: redirect('http://www.meu.safirasaloes.com.br/%{professional_website}')

  mount Split::Dashboard, at: 'testes_ab'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates_presence_of :nome, :email, :telefone, :profissao, :endereco
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    logger.info "***AGENT: #{request.user_agent}"
    @customer = Customer.new
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.save

    respond_to do |format|
      format.js { render "modal_response" }
    end
  end

  def obrigado
  end

  def google8346493cd4fccd96
    render :layout => false
  end

  def track_video_played
    finished(:video_position)
    respond_to do |format|
      format.js { head :ok }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:nome, :email, :telefone, :dispositivo, :price, :profissao, :endereco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  @@prices = {
    low: {indiv: '39,90', basic: '69,90', busin: '99,90', empire: '139,90'},
    medium: {indiv: '49,90', basic: '79,90', busin: '109,90', empire: '159,90'},
    high: {indiv: '59,90', basic: '99,90', busin: '139,90', empire: '199,90'}
  }

  def get(price, plan)
    @@prices[price.to_sym][plan.to_sym]
  end

end

app/views/customers/_crazyegg.html.erb
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0017/9522.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

app/views/customers/_footer.html.erb
<footer id="footer">
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 "> &copy; Copyright 2015 by SafiraSalões. Todos os direitos reservados. </div>
          <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
            <ul class="contact-us">
              <li>
                <i class="fa fa-map-marker"></i>
                <p> 
                  <strong class="contact-pad">Endereço:</strong> Av dos Engenheiros, 431, sala 802 - Castelo,<br> Belo Horizonte - Minas Gerais <br>
                </p>
              </li>
              <li>
                <i class="fa fa-envelope"></i>
                <p><strong>Email:</strong><a href="mailto:contato@safirasaloes.com.br">contato@safirasaloes.com.br</a></p>
              </li>
            </ul>
          </div>
        </div>
      </div>
  </div>
  <%# render "webengage" %>
</footer>
<a href="#" class="scrollup"><i class="fa fa-angle-up"></i></a>

app/views/customers/_subscribe_form.html.erb
<%= form_for @customer, html: { class: "reply", id: "contact" } do |f| %>
   <fieldset>
      <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= f.text_field :nome, class: "form-control small", value: "", required: true, placeholder: "Nome" %>
         </div>
      </div>
      <div class="row">
         <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
            <%= f.email_field :email, class: "form-control small", value: "", required: true, placeholder: "E-mail" %>
         </div>
         <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <%= f.text_field :telefone, class: "form-control small telefone", value: "", required: true, placeholder: "Telefone" %>
         </div>
      </div>
      <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= f.text_field :endereco, class: "form-control small", value: "", required: true, placeholder: "Endereço Completo" %>
         </div>
      </div>
      <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= f.text_field :profissao, class: "form-control small", value: "", required: true, placeholder: "Profissão (Cabeleireiro, Manicure / Pedicure, Esteticista...)" %>
         </div>
      </div>
      <%= f.hidden_field :dispositivo, value: request.user_agent %>
      <%= f.hidden_field :price %>
   </fieldset>
   <%= f.submit 'Eu Quero mais Clientes AGORA!', class: "btn-small btn-color btn-extended submit  bottom-pad" %>
   <div class="clearfix"></div>
<% end %>

app/views/customers/_webengage.html.erb
<div id='_webengage_script_tag'></div>
<script  type="text/javascript">
  var _weq = _weq || {};
  _weq['webengage.licenseCode'] = '14507c0cd';
  _weq['webengage.widgetVersion'] = "4.0";
  
  (function(d){
    var _we = d.createElement('script');
    _we.type = 'text/javascript';
    _we.async = true;
    _we.src = (d.location.protocol == 'https:' ? "https://ssl.widgets.webengage.com" : "http://cdn.widgets.webengage.com") + "/js/widget/webengage-min-v-4.0.js";
    var _sNode = d.getElementById('_webengage_script_tag');
    _sNode.parentNode.insertBefore(_we, _sNode);
  })(document);
</script>

app/views/customers/modal_response.js.erb
<% if @customer.persisted? || @customer.errors.added?(:email, :taken) %>
  location.href = "<%= obrigado_url %>"
<% else %>
  <% if @customer.errors.added?(:nome, :blank) ||
        @customer.errors.added?(:email, :blank) ||
        @customer.errors.added?(:telefone, :blank) ||
        @customer.errors.added?(:endereco, :blank) ||
        @customer.errors.added?(:profissao, :blank) %>
    $('#modal-body').prepend('<div class="error">Preencha todos os campos</div>')
  <% else %>
    $('#myModal').toggle()
    $('#myModalFail').modal('show')
  <% end %>
<% end %>

app/views/customers/obrigado.html.erb
<div class="wrap">
  <header id="header">
    <div class="main-header">
      <div class="container" id="myScrollSpy">
        <div class="logo pull-left">
          <h1>
            <%= link_to image_tag('logo.png'), root_path %>
          </h1>
        </div>
      </div>
    </div>
  </header>
</div>

<div class="content">
  <div class="container">
    <div class="row" id="align-central">
      <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12" id="contact-form">
        <h3 class="title">Obrigado</h3>
          <p>
            Obrigado pelo seu interesse em utilizar o SafiraSalões. <b>Entraremos em contato em breve.</b>
          </p>
          <p>
            Enquanto aguarda, <a href="https://www.facebook.com/SafiraSaloes">curta nossa página no Facebook</a> para conhecer mais sobre o SafiraSalões.
          </p>

          <p>
            Obrigado!
          </p>
        <div class="divider"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>      <html class="ie ie8"> <![endif]-->
<!--[if IE 9]>      <html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->  <html> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta property="fb:app_id" content="680919752037576" />
  <title>Conquiste e Fidelize clientes automaticamente | SafiraSalões</title>
  <meta name="keywords" content="divulgação para salão de beleza, sistema para salão de beleza, marketing para salão de beleza, sistema para cabeleireiro, marketing para salões de beleza, sistema para salões de beleza">
  <meta name="description" content="O SafiraSalões foi feito pra você, profissional da beleza, que deseja conquistar e fidelizar clientes de modo ridiculamente simples e automático">
  <meta name="author" content="SafiraSalões - Conquista e Fideliza clientes para profissionais da beleza automaticamente">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="alternate" href="safirasaloes.com.br" hreflang="pt-br" />
  <%= render "hotjar.html" if Rails.env.production? %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "woopra.html" if Rails.env.production? %>
  <%= favicon_link_tag 'favicon.png', rel: "shortcut icon" %>
  
  <%= render "fb_pixel" if Rails.env.production? %>
</head>
<body class="home" data-spy="scroll" data-offset="250" data-target="#myScrollSpy">

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= render "footer" %>
</div>

</body>
</html>